### ISSUE TITLE
Will not allow equipping 4x S4 on Sabre

### ISSUE THREAD

**Issue by stevencheatham** [dolkensp/HoloXPLOR#11]
Will not allow equipping 4x S3 on Sabre.  Even after unequipping the S3 gimbals it will not allow a S3 weapon in the slot.   Halotable allows this however.  Please fix =)

EDIT: This is now working.

**Comment by dolkensp** [comment]
Are you comparing to live, or PTU?

At this stage, I am unable to equip size 4 weapons in PTU, and I know that the S3 gimbal that was on live, was a special gimbal that didn't cause a shrink in size (S3 -> S3, as opposed to S4 -> S3 as you'd expect).

If you're testing ptu, please use https://ptu.holoxplor.space

Apart from that, the Sabre is behaving the same both in-game and in HoloXPLOR for me

**Comment by NuclearMessiah** [comment]
You could never equip size 4 to the sabre and the gimbals on it are special not the normal kind so the Sabre can t most ever equip 4 size 3s

**Comment by stevencheatham** [comment]
This is no longer an issue in the current build
