### ISSUE TITLE
Cannot equip five size 2 weapons on the Super Hornet in Live.

### ISSUE THREAD

**Issue by BuckMaster365** [dolkensp/HoloXPLOR#13]
I removed the Canard Mount on the nose.  Put a S3 gimble on the nose.  I want to put a size 2 Tarantula 870 on the S3 nose gimble but - it will not let me.  The ship ends up being minus one 870.

**Comment by dolkensp** [comment]
Are any of the guns you're using taken from other ships?

I've had no issues using REC rented items on a SuperHornet, but taking items from other ships can sometimes be problematic

**Comment by BuckMaster365** [comment]
You already fixed this problem Peter. I am no longer having this issue.
Thank you for the follow up.

**Comment by dolkensp** [comment]
Awesome, thanks

**Comment by BuckMaster365** [comment]
With the new push to live   the same prob is back again in the Live Verse.
Replace the canard with a S3 Gimble and the SH will not equip the 5th 870.
  Keep up the good (and very cool) work.  We appreciate you.  :-)
