### ISSUE TITLE
Dataforge exe unhandled exception with live dataforge.pak files.

### ISSUE THREAD

**Issue by AngryProgrammerInside** [dolkensp/HoloXPLOR#16]
```
Unhandled Exception: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadChar()
   at Dolkens.Framework.BinaryExtensions.ExtensionMethods.ReadCString(BinaryReader binaryReader)
   at HoloXPLOR.DataForge.DataForgeSerializer.ReadFile(String inFile)
   at HoloXPLOR.DataForge.Program.Main(String[] args)

```
Error encountered when attempting to use the files from the latest dataforge.pak on live. The dataforge -> xml still works with the 2.2.0a PTU files but not the current live release.

**Comment by dolkensp** [comment]
Which file exactly? I'm not having any issues.

You've extracted the pak out to the individual files right?

I was able to convert both the Game.dcb, and a bunch of the CryXmlB files without issue.

**Comment by AngryProgrammerINside** [comment]
Nevermind, PEBKAC

**Comment by dolkensp** [comment]
No worries. Thanks for letting me know.
