### ISSUE TITLE
Can't load S3 Shields on the Sabre

### ISSUE THREAD

**Issue by RedLir** [dolkensp/HoloXPLOR#17]
Hey there,

I was using your tool as a workaround in 2.2.0 to attach the seco_S3_f4_DD shield ( INK-Mark 304-ID) to the Sabre.

As of patch 2.2.1 I can't seem to do this anymore.  When I select the new shield to drag it into the slot, nothing lights up and it won't attach.

**Comment by dolkensp** [comment]
I recommend deleting your XML file, and getting a fresh one by re-launching the hangar.

I haven't had a chance to check, but SC is trying to move towards 3xS1 shields instead of 1xS3 shield for the Sabre. Not sure if they've done that this patch, but if they have, then you won't be able to put the S3 shield on the Sabre.

**Comment by dolkensp** [comment]
Actually, I just checked your profile - it seems CIG has deliberately locked out those shields:

`data-item-required-port-tags="Component_Refactor_Lock"`

Not too much I can do at this stage, as I don't want to override CIGs rules, as then it may fall out of favor with them.

Sorry :(

**Comment by dolkensp** [comment]
You can override it yourself by opening the Developer Tools window, going to the console, and entering this snippet

`$('[data-item-required-port-tags="Component_Refactor_Lock"]').data('item-required-port-tags', '')`

**Comment by RedLir** [comment]
Where are you seeing this entry 

data-item-required-port-tags="Component_Refactor_Lock"

I don't see it in the database file, and a grepwin of the entire SC folder finds nothing.

Thanks

**Comment by dolkensp** [comment]
In C:\Users\Peter\SkyDrive\Workspaces\HoloXPLOR\HoloXPLOR\App_Data\Scripts\Entities\Items\XML\Spaceships\Shields\SECO\SECO_S3_F4_DD.xml

Line 6: <param name="requiredPortTags" value="Component_Refactor_Lock" />
