### ISSUE TITLE
Ship image doesn't load

### ISSUE THREAD

**Issue by joecasanova** [dolkensp/HoloXPLOR#2]
I get this when attempting to load my Hornet F7C:  https://www.thelonegamers.com/wp-content/uploads/2016/01/2016-01-30-14_41_47-Greenshot.jpg

This is the image address:  http://placehold.it/800x600

Let me know what other details I can provide.

**Comment by dolkensp** [comment]
Hey joe - no styles (beyond base bootstrap for homescreen) or images are completed yet.

Working on it though.

Ship images will likely come much later - I'm actually hoping to pull in the 3D models that I'm exporting with the work I've been doing with Markemp here: https://github.com/Markemp/Cryengine-Converter

Thanks for the report though - will leave it open until I've got either static or 3d images in.

**Comment by joecasanova** [comment]
Thanks for the quick response!  I've got this tool bookmarked and I'll definitely be keeping an eye on it.  Very promising.

**Comment by dolkensp** [comment]
Placeholder images in place for now.
