### ISSUE TITLE
Sabre shield not swappable with Cutlass/SH shields

### ISSUE THREAD

**Issue by Balothar12** [dolkensp/HoloXPLOR#20]
Sabre shields can't be swapped for the SH/Cutlass default shields anymore, despite all three of them being the same size.

**Comment by dolkensp** [comment]
CIG has locked down many/all shields at the moment - beyond just the holotable not working, they've actually added flags to prevent shields from being equipped at the moment.

For now, I'm not removing these flags - We'll see what they release next patch, as I suspect there's good reason for it.

If nothing changes in the next patch, I'll revisit.
