### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by jessewhisenhunt** [dolkensp/HoloXPLOR#21]
when i look for the database user file, i can not find it even after searching pc and there are no hidden files either

**Comment by dolkensp** [comment]
You must log into the hangar first, before the file will appear.

It will be named something like "4D42AC.xml"


Peter Dolkens

**Comment by dolkensp** [comment]
Hi @jessewhisenhunt did you have any luck with this?

Closing for now, unless you let me know you're still having troubles.
