### ISSUE TITLE
Weapon range ?

### ISSUE THREAD

**Issue by Vaalaa** [dolkensp/HoloXPLOR#23]
Why there is no weapon range ? Holotable do have them... :)

Thank you !

**Comment by Vaalaa** [comment]
Right now. Don't know if it's because of 2.3 live but weapon doesn't show damage / hit, weapon DPS and no weapon range. Missing many crucial information...

Fix ? thank you !

**Comment by dolkensp** [comment]
Yup, 2.3 changes where that information is stored, and I'm away for Easter with only my phone.

I'll be back on Monday, and able to update to point at the new ammo.


Peter Dolkens

**Comment by Vaalaa** [comment]
awesome ! Happy Easter BTW !

**Comment by dolkensp** [comment]
This has been added for the majority of weapons.

Combine Ballistic I think is only one having issues right now, but I'll look into it further tomorrow.
