### ISSUE TITLE
Under Shield section no hull armor ?

### ISSUE THREAD

**Issue by Vaalaa** [dolkensp/HoloXPLOR#24]
We got shield but what about the hull armor ? ( it's do for Hornet ) But not for Karthu-Al ?

**Comment by dolkensp** [comment]
Not all ships have armour

Hornet, Aurora, and 300 sites only from memory, and the armour is locked to the ships too.

Will have to wait on CIG for that one


Peter Dolkens

**Comment by Vaalaa** [comment]
ok
