### ISSUE TITLE
"Hangar removed"

### ISSUE THREAD

**Issue by Konas14** [dolkensp/HoloXPLOR#27]
despite clearing my SC > Public > USER > Database folder and reloading my hangar several times i am unable to load my avenger stalker using HoloXPLOR at the following link despite clearing and re-uploading the file
https://holoxplor.space/HoloTable/Konas
I am using Chrome and can open the Freelancers and Hornet (didn't buy the hornet with $$ or REC so no idea why its an option anyway) but attempting to open the Avenger produces the following error
"Error.
The hangar you requested has been removed.
This is normal. I remove existing inventories regularly to save space, and reduce any security risks.

Please re-upload your file and try again."

Any help would be appreciated!

**Comment by dolkensp** [comment]
Thanks, this is a caching issue, which I can fix for future users from my end, but for you, you'll need to clear your browser cache.

For chrome, ctrl+shift+delete should bring up the prompt.


Peter Dolkens

**Comment by Konas14** [comment]
Awesome. Thanks for the help

Gene

**Comment by dolkensp** [comment]
I've adjusted the caching rules around deleted hangars - this shouldn't happen any longer
