### ISSUE TITLE
Help not very tech savey

### ISSUE THREAD

**Issue by Lafl1dav** [dolkensp/HoloXPLOR#28]
I tried to use the holoxplor got to my ships and made my changes and downloaded it, went to get in game and  check things at the hanger holo table  and after 1:00 to 2:00 minutes the game now freezes and a hum comes out speakers can not use ctrl alt delete at all must shut down power manually
and restart. tried to get in game arena commander same thing happens very bummed and the game never reacted this way before. Do not know if there is issue  with what I have done or if it is the game
all I know is that it never has reacted this way before. I am member of xplor and was told to try your holo 
because the game one has so many issues and your was a better option to use for load outs. fallowed your instructions but not sure if maybe did something wrong on my part. have the same look as just812(bug)  don't know if that can be deleted or not?  Please help if you can
Dave
<?xml version="1.0"?>
-<player Version="6" class="Player" oemId="00000000-0000-0000-0000-000000000000" id="ffa93e0c-0000-0000-0000-000000000000" currVehicleOwner="1" currSeatId="1" __DSID__currVehicleDID="00a93e0c-005d-6a29-0100-000000000000">-<ship class="DefaultSpaceShips.ORIG.ORIG_325a" oemId="00000000-0000-0000-0000-000000000000" id="00a93e0c-005d-6a29-0100-000000000000" acMembershipId="19491421" acRentalEquipment="0" respawnable="0" name="Ship_0">-<inventory count="54"><item __EID__id="00a93e0c-005d-6a29-0101-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0102-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0103-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0104-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0105-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0106-000000000000"/><item __EID__id="00a93e0c-005d-6a29-010b-000000000000"/><item __EID__id="00a93e0c-005d-6a29-010c-000000000000"/><item __EID__id="00a93e0c-005d-6a29-010d-000000000000"/><item __EID__id="00a93e0c-005d-6a29-010e-000000000000"/><item __EID__id="00a93e0c-005d-6a29-010f-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0110-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0111-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0112-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0113-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0114-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0115-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0116-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0117-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0118-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0119-000000000000"/><item __EID__id="00a93e0c-005d-6a29-011a-000000000000"/><item __EID__id="00a93e0c-005d-6a29-011b-000000000000"/><item __EID__id="00a93e0c-005d-6a29-011c-000000000000"/><item __EID__id="00a93e0c-005d-6a29-011d-000000000000"/><item __EID__id="00a93e0c-005d-6a29-011e-000000000000"/><item __EID__id="00a93e0c-005d-6a29-011f-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0120-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0121-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0122-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0123-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0124-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0125-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0126-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0127-000000000000"/><item __EID__id="00a93e0c-005d-6a29-012b-000000000000"/><item __EID__id="00a93e0c-005d-6a29-012c-000000000000"/><item __EID__id="00a93e0c-005d-6a29-012d-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0130-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0133-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0135-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0107-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0108-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0109-000000000000"/><item __EID__id="00a93e0c-005d-6a29-010a-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0128-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0134-000000000000"/><item __EID__id="00a93e0c-005d-6a29-012e-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0136-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0131-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0132-000000000000"/><item __EID__id="00a93e0c-005d-6a29-012f-000000000000"/><item __EID__id="00a93e0c-005d-6a29-0129-000000000000"/><item __EID__id="00a93e0c-005d-6a29-012a-000000000000"/>

**Comment by dolkensp** [comment]
I've never had any similar reports from broke using holoxplor.

I do know the game can hang like that sometimes though, separate from my app. If you have a second screen, you can terminate star citizen when it happens, because your computer is still working, the problem is, when star citizen hands like this, it leaves a black overlay on your main monitor until it is terminated.

If you have a second screen, you can normally move the mouse and any Windows to the second screen which will let you terminate things.


Peter Dolkens

**Comment by dolkensp** [comment]
I recommend you try it again either way, hangs like that are fairly rare, so you should be ok.


Peter Dolkens
