### ISSUE TITLE
Cutlass Fixed Mount Problem

### ISSUE THREAD

**Issue by DoctorDigital** [dolkensp/HoloXPLOR#29]
Hi there,
described it in the thread on the RSI forums:

I rented the Cutlass Fixed Mount. When I equip it to the Culass Black, the size4 weapons slot does not show up. If I replace it again with the Cutlass Turret, the turret get's in place and attaches its weapons. If I reequip the fixed mount, the size4 slot will not getcreated, so I cannot attach a gun to it.

It seems to work with the sample file, that is provided on the webpage.

**Comment by dolkensp** [comment]
This is a know issue - the XML turbulent is sending down unfortunately is missing a bunch of slots.

Traditionally, HoloXPLOR has only ever moved XML sections around, never created or deleted sections. Unfortunately, it's become quite common recently for rental items to come down without item slots. The HoloTable used to automatically fix it, and it's planned to add that functionality to HoloXPLOR.

**Comment by dolkensp** [comment]
This should be fixed - let me know if it's still an issue

**Comment by DoctorDigital** [comment]
Hmmm... Still doesn't work for me. Even deleted the XML and let the game create a fresh one.

**Comment by dolkensp** [comment]
Can you let me know your forum handle, so I can investigate your file in
particular.

Thanks

**Comment by DoctorDigital** [comment]
Forum Handle is: DoctorDigital. Community Monicker: Friedrich Nix. Could be that I erased my Data. I can provide you with the XML via Email or reupload.

**Comment by dolkensp** [comment]
If you RE upload I should be able to find it, otherwise shoot through email to plugins@ddrit.com

Don't take too long though, sounds like CIG is sending 2.4 into internal QA, not long now!


Peter Dolkens

**Comment by DoctorDigital** [comment]
I reuploaded the file. Nevertheless is another "free fly week" and I believe that's the time when all configs get new data anyways. But thank you so much for your time an patience!
