### ISSUE TITLE
Shield swapping does not work.

### ISSUE THREAD

**Issue by DoctorDigital** [dolkensp/HoloXPLOR#30]
Equipping different shields or reequipping shields does not work.

I have a rental size 4 shield. I cannot equip that shield to a size 4 slot (Hornet for example). When I remove the Hornet shield, I cannot equip either the size 4 shield to the empty slot, nor can I reequip the original shield.

When directly editing the XML file, the shield is equipable and is shown correctly in holoXPLOR. Also I believe the newly equipped shield is working as intended in game.

**Comment by dolkensp** [comment]
CIG has deliberately disabled most shields currently - manually hacking the XML allows for all sorts of loadouts. See #17 for more details.
