### ISSUE TITLE
game.dcb

### ISSUE THREAD

**Issue by E95Predator** [dolkensp/HoloXPLOR#34]
Hi, HoloXPLOR.DataForge can decode game.dcb (StarCitizen), is it an a issue or it's impossible?

**Comment by dolkensp** [comment]
You'll need to build from latest source - I haven't packaged a release with the latest version just yet, but the fixes are already in the source code.

**Comment by E95Predator** [comment]
The issue that crash app is if (!record.FileName.Contains(record.Name)).  Thx for the response!
