### ISSUE TITLE
Many functions not working on graphical interface

### ISSUE THREAD

**Issue by DoctorDigital** [dolkensp/HoloXPLOR#4]
Hello,
I really love that project, that I just recently discoverd. Since my Holotable in Star Citizen Alpha is massively broken, you have provided the first managable solution for equipping my ships.

After you upgraded your page yesterday do a more graphic version, I encountered a bunch of flaws while outfitting the ships.

1. drag and drop weapons does not seem to work all the time. Sometimes equipment does not equip at all (NV4 Turret of Superhornet) and sometimes it takes two or three drags to show the equipped weapon in its slot. Also the count does not go down accordingly.

2. There must be an error when equipping a shield. It looks like an error in HTML and/or scripts.

Keep up the awesome work. I am very willing to test and give feedback. It would be awesome, to be able to use the last working version of the page, because I actually use it in Arena Commander!

Thanks and keep it up! Awesome work!

**Comment by dolkensp** [comment]
Hi,

I've just rolled out some advanced logging, as well as fixing a debugging error I had left in yesterday.

Could you re-try and let me know if it persists - hopefully it's fixed, and if not, I should get some error reports back.

Thanks

**Comment by DoctorDigital** [comment]
Hey! Good work! Everything is running flawlessly now.
Fitted a bunch of different things, shield, various weapons on various ships. All worked flawlessly!

Great! Really good job!

Now - if you want something to be tested, which I can assist you, please let me know! I will gladly try and give you as much feedback as I can.

**Comment by dolkensp** [comment]
Thanks - At the moment the changes are mostly small / informational (New stats when hovering, tweaking styles, etc)

The new error reporting emails me, and saves a copy to file, and so far no-one has triggered it with the latest build, except for me in deliberate tests.

I'll let you know if there's anything else that needs testing though. Thanks
