### ISSUE TITLE
Sensitive Information uploaded

### ISSUE THREAD

**Issue by Nikmyth** [dolkensp/HoloXPLOR#9]
Could you please remove my USERIDs and "hangar owner" information from your database?
It seems I did not have the full information that this info would be uploaded into your database. 
It would be greatly apreciated.
Kind Regards.

**Comment by dolkensp** [comment]
I delete all files every 2-3 days. You'll be home in the next purge.


Peter Dolkens

**Comment by dolkensp** [comment]
I've purged the last few days of data, and added delete functionality, if you were missed in that batch.

I don't purge the last 48 hours just in-case someone is still actively editing their files in that period.
